# FASE 1 - PASO 1.1 - PUNTO 1.1.3
# Configuración del Servidor Web
# Puerto 8080 y Context Path /api
server.port=8080
server.servlet.context-path=/api

# Configuración de la Base de Datos (MySQL - cita_med_db)
# Reemplaza 'root' y 'password' con tus credenciales de MySQL
spring.datasource.url=jdbc:mysql://@localhost:3306/cita_med_db
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA/Hibernate
# Deshabilitamos la generación automática de tablas (ddl-auto=none)
# ya que la BD y los SPs se crearon en la FASE 0.
spring.jpa.hibernate.ddl-auto=none
# Muestra el SQL generado por JPA (útil para debug)
spring.jpa.show-sql=true
# Dialecto específico para MySQL 8+
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# FASE 1 - PASO 1.5.5
# Configuración de Seguridad JWT
# Este es un secreto de 64 bytes (512 bits) generado aleatoriamente.
# (Requerido por el roadmap en un paso futuro, se añade ahora por completitud)
jwt.secret=7A25432A462D4A614E645267556B58703273357638792F423F4528482B4D6251655468576D5A7134743777217A34743A